# Essential MySQL Functions

In [2]:
import os
from dotenv import load_dotenv

import pandas as pd
import sqlalchemy

In [3]:
load_dotenv()

db_host = os.environ.get("db_host")
db_user = os.environ.get("db_user")
db_password = os.environ.get("db_password")

In [4]:
engine = sqlalchemy.create_engine(f"mysql+pymysql://{db_user}:{db_password}@{db_host}:3306/sql_store")

In [5]:
pd.read_sql("SHOW TABLES", con= engine)

  Tables_in_sql_store
0           customers
1    order_item_notes
2         order_items
3      order_statuses
4              orders
5            products
6            shippers

## Numeric Functions

In [6]:
pd.read_sql("SELECT ROUND(5.3763, 2)", con= engine)

   ROUND(5.3763, 2)
0              5.38

In [7]:
pd.read_sql("SELECT TRUNCATE(5.3763, 2) ", con= engine)

   TRUNCATE(5.3763, 2)
0                 5.37

In [8]:
pd.read_sql("SELECT CEILING(5.7) ", con= engine)

   CEILING(5.7)
0             6

In [9]:
pd.read_sql("SELECT FLOOR(5.7) ", con= engine)

   FLOOR(5.7)
0           5

In [10]:
pd.read_sql("SELECT ABS(-5.2) ", con= engine)

   ABS(-5.2)
0        5.2

In [11]:
pd.read_sql("SELECT RAND() ", con= engine)

     RAND()
0  0.750712

## String Functions

In [12]:
pd.read_sql("SELECT LENGTH('ARMAN') ", con= engine)

   LENGTH('ARMAN')
0                5

In [13]:
pd.read_sql("SELECT LOWER('ARMAN')", con= engine)
pd.read_sql("SELECT UPPER('arman')", con= engine)

  UPPER('arman')
0          ARMAN

In [14]:
pd.read_sql("SELECT LTRIM('      ARMAN')", con= engine)
pd.read_sql("SELECT RTRIM('ARMAN      ')", con= engine)
pd.read_sql("SELECT TRIM('   ARMAN      ')", con= engine)

  TRIM('   ARMAN      ')
0                  ARMAN

In [15]:
pd.read_sql("SELECT LEFT('arman salehi', 5)", con= engine)
pd.read_sql("SELECT RIGHT('arman salehi', 5)", con= engine)
pd.read_sql("SELECT SUBSTRING('arman salehi', 3, 7)", con= engine)

  SUBSTRING('arman salehi', 3, 7)
0                         man sal

In [16]:
pd.read_sql("SELECT LOCATE('m','arman')", con= engine)

   LOCATE('m','arman')
0                    3

In [17]:
pd.read_sql("SELECT REPLACE('arman salehi', 'arman', 'mahan')", con= engine)

  REPLACE('arman salehi', 'arman', 'mahan')
0                              mahan salehi

In [18]:
pd.read_sql("SELECT CONCAT('arman', ' salehi')", con= engine)

  CONCAT('arman', ' salehi')
0               arman salehi

## Date Functions in MySQL

In [19]:
pd.read_sql("SELECT NOW(), CURDATE(), CURTIME()", con= engine)

                NOW()   CURDATE()       CURTIME()
0 2026-05-22 15:17:22  2026-05-22 0 days 15:17:22

In [20]:
pd.read_sql("SELECT YEAR(NOW())", con= engine)
pd.read_sql("SELECT MONTH(NOW())", con= engine)
pd.read_sql("SELECT DAY(NOW())", con= engine)
pd.read_sql("SELECT HOUR(NOW())", con= engine)
pd.read_sql("SELECT MINUTE(NOW())", con= engine)
pd.read_sql("SELECT SECOND(NOW())", con= engine)

   SECOND(NOW())
0             22

In [21]:
pd.read_sql("SELECT DAYNAME(NOW())", con= engine)
pd.read_sql("SELECT MONTHNAME(NOW())", con= engine)

  MONTHNAME(NOW())
0              May

In [22]:
pd.read_sql("SELECT EXTRACT(DAY FROM NOW())", con= engine)

   EXTRACT(DAY FROM NOW())
0                       22

## Formatting Dates and Times

In [23]:
pd.read_sql("SELECT DATE_FORMAT(NOW(), '%%M %%d %%Y')", con= engine)

  DATE_FORMAT(NOW(), '%M %d %Y')
0                    May 22 2026

In [24]:
pd.read_sql("SELECT TIME_FORMAT(NOW(), '%%H:%%i %%p')", con= engine)

  TIME_FORMAT(NOW(), '%H:%i %p')
0                       15:17 PM

In [25]:
pd.read_sql("SELECT DATE_ADD(NOW(), INTERVAL 1 YEAR)", con= engine)

  DATE_ADD(NOW(), INTERVAL 1 YEAR)
0              2027-05-22 15:17:22

In [26]:
pd.read_sql("SELECT DATE_ADD(NOW(), INTERVAL -1 YEAR)", con= engine)

  DATE_ADD(NOW(), INTERVAL -1 YEAR)
0               2025-05-22 15:17:22

## Calculating Dates and Times

In [27]:
pd.read_sql("SELECT DATEDIFF('2019-01-05', '2019-01-01')", con= engine)

   DATEDIFF('2019-01-05', '2019-01-01')
0                                     4

In [28]:
pd.read_sql("SELECT TIME_TO_SEC('09:00')", con= engine)

   TIME_TO_SEC('09:00')
0                 32400

## IFNULL and COALESCE Functions

In [29]:
query = """
select 
	order_id,
    ifnull(shipper_id, "not assigned") as shipper
from orders
"""

pd.read_sql(query, con= engine)

   order_id       shipper
0         1  not assigned
1         3  not assigned
2         4  not assigned
3         6  not assigned
4         8  not assigned
5         9             1
6        10             2
7         5             3
8         2             4
9         7             4

In [30]:
query = """
select 
	order_id,
    coalesce(shipper_id, comments, "not assigned") as shipper
from orders
"""

pd.read_sql(query, con= engine)

   order_id                                            shipper
0         1                                       not assigned
1         2                                                  4
2         3                                       not assigned
3         4                                       not assigned
4         5                                                  3
5         6                  Aliquam erat volutpat. In congue.
6         7                                                  4
7         8  Mauris enim leo, rhoncus sed, vestibulum sit a...
8         9                                                  1
9        10                                                  2

## IF Function
`IF(expression, expr_true, expr_false)`

In [ ]:
query = """
select 
	order_id,
    if(sum(quantity) > 1, "many times", "ones") as frequency
from orders oi
"""

pd.read_sql(query, con= engine)

EXERCISE:

In [31]:
query = """
select 
	oi.product_id,
    p.name,
	sum(quantity) as orders,
    if(sum(quantity) > 1, "many times", "ones") as frequency
from order_items oi
join products p using(product_id)
group by (product_id)
order by product_id
"""

pd.read_sql(query, con= engine)

   product_id                          name  orders   frequency
0           1             Foam Dinner Plate    16.0  many times
1           2     Pork - Bacon,back Peameal     7.0  many times
2           3      Lettuce - Romaine, Heart    28.0  many times
3           4  Brocolinni - Gaylan, Chinese     8.0  many times
4           5        Sauce - Ranch Dressing     3.0  many times
5           6                Petit Baguette     7.0  many times
6           8      Island Oasis - Raspberry     2.0  many times
7           9                        Longan     9.0  many times
8          10                  Broom - Push     7.0  many times

## The Case Operator

In [34]:
query = """
select 
	order_id,
	CASE
		WHEN YEAR(order_date) = YEAR(NOW()) THEN 'active'
		WHEN YEAR(order_date) = YEAR(NOW())-1 THEN 'last year'
		WHEN YEAR(order_date) < YEAR(NOW())-1 THEN 'archived'
		ELSE 'future'
	END AS category
from orders
"""

pd.read_sql(query, con= engine)

   order_id  category
0         1  archived
1         2  archived
2         3  archived
3         4  archived
4         5  archived
5         6  archived
6         7  archived
7         8  archived
8         9  archived
9        10  archived